---
abstract: 'Consume XML with Moose and xpath queries'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
build_requires:
  English: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Rabbit
requires:
  Data::Visitor::Callback: 0
  Encode: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Role::Parameterized: 0
  Perl6::Junction: 0
  Scalar::Util: 0
  XML::LibXML: 1.70
  perl: 5.008
resources:
  repository: git://github.com/robinsmidsrod/XML-Rabbit.git
version: 0.0.1
